<?php
/**
 * Dynamically grants or revokes WP capabilities for ReadMeWP CPT actions.
 *
 * Covers two scenarios:
 *
 * 1. Owner lock — if a README is set to "only I can edit this", WordPress
 *    edit/delete caps are stripped from all other users for that post.
 *
 * 2. Creator setting — the settings page allows specific roles/users to
 *    create (publish) READMEs. This class grants the custom CPT caps to
 *    those users at runtime without touching unrelated admin capabilities.
 *
 * Custom CPT caps generated by capability_type => ['readmewp','readmewps']:
 *   edit_readmewp          — edit a specific post (meta cap, needs post ID)
 *   edit_readmewps         — edit own posts list
 *   edit_others_readmewps  — edit posts owned by others
 *   publish_readmewps      — publish (create) new posts
 *   read_readmewp          — read a specific post
 *   delete_readmewp        — delete a specific post
 *   delete_readmewps       — delete own posts
 *
 * @package ReadMeWP
 */

declare( strict_types=1 );

namespace ReadMeWP;

defined( 'ABSPATH' ) || exit;

/**
 * Class Access
 */
class Access {

	/**
	 * Primitive caps we grant to allowed creators.
	 */
	private const CREATOR_CAPS = array(
		'edit_readmewps',
		'publish_readmewps',
	);

	/**
	 * Hook into WordPress.
	 */
	public function register(): void {
		// Grant CPT caps to admins (they have no native readmewp* caps).
		add_filter( 'user_has_cap', array( $this, 'grant_admin_caps' ), 5, 4 );
		// Apply owner lock and creator grants after WP's own meta cap mapping.
		add_filter( 'user_has_cap', array( $this, 'filter_caps' ), 20, 4 );
	}

	/**
	 * Give administrators all ReadMeWP CPT caps automatically.
	 * Without this they'd get access denied on the CPT list screen.
	 *
	 * @param bool[]   $allcaps All caps the user has.
	 * @param string[] $caps    Primitive caps being checked.
	 * @param array    $args    [0] => requested cap, [1] => user_id, [2] => object_id.
	 * @param \WP_User $user    The user object.
	 * @return bool[]
	 */
	public function grant_admin_caps( array $allcaps, array $caps, array $args, \WP_User $user ): array {
		if ( empty( $allcaps['manage_options'] ) ) {
			return $allcaps;
		}

		// Grant all readmewp* primitive caps to admins.
		foreach ( $caps as $cap ) {
			if ( str_contains( $cap, 'readmewp' ) ) {
				$allcaps[ $cap ] = true;
			}
		}

		return $allcaps;
	}

	/**
	 * Enforce owner lock and grant creator caps to non-admins.
	 *
	 * @param bool[]   $allcaps All caps the user has.
	 * @param string[] $caps    Primitive caps being checked.
	 * @param array    $args    [0] => requested cap, [1] => user_id, [2] => object_id.
	 * @param \WP_User $user    The user object.
	 * @return bool[]
	 */
	public function filter_caps( array $allcaps, array $caps, array $args, \WP_User $user ): array {
		$requested = $args[0] ?? '';
		$user_id   = (int) ( $args[1] ?? 0 );
		$post_id   = isset( $args[2] ) && is_numeric( $args[2] ) ? (int) $args[2] : 0;

		// ---------------------------------------------------------------
		// 1. Owner lock — strip edit/delete from non-owners on locked posts.
		// ---------------------------------------------------------------
		if ( $post_id > 0 ) {
			$post = get_post( $post_id );
			if (
				$post &&
				Post_Type::SLUG === $post->post_type &&
				in_array( $requested, array( 'edit_post', 'delete_post' ), true ) &&
				Ownership::is_owner_only( $post_id ) &&
				! Ownership::is_owner( $post_id, $user_id )
			) {
				foreach ( $caps as $cap ) {
					$allcaps[ $cap ] = false;
				}
				return $allcaps;
			}
		}

		// ---------------------------------------------------------------
		// 2. Skip admins — they already have everything from grant_admin_caps.
		// ---------------------------------------------------------------
		if ( ! empty( $allcaps['manage_options'] ) ) {
			return $allcaps;
		}

		// ---------------------------------------------------------------
		// 3a. Grant list-screen access to any non-admin who can read at
		// least one README. Without edit_readmewps, WordPress redirects
		// the user away from edit.php?post_type=readmewp to the first
		// accessible submenu instead of showing the list.
		// We intentionally do NOT grant publish_readmewps here, so the
		// "Add New" button stays hidden for read-only users.
		// ---------------------------------------------------------------
		$needs_list_cap = false;
		foreach ( $caps as $cap ) {
			if ( 'edit_readmewps' === $cap ) {
				$needs_list_cap = true;
				break;
			}
		}

		if ( $needs_list_cap && empty( $allcaps['edit_readmewps'] ) ) {
			static $readable_cache = array();
			if ( ! isset( $readable_cache[ $user_id ] ) ) {
				$perms                      = new Permissions();
				$readable_cache[ $user_id ] = ! empty( $perms->get_readable_posts( $user_id ) );
			}
			if ( $readable_cache[ $user_id ] ) {
				$allcaps['edit_readmewps'] = true;
			}
		}

		// ---------------------------------------------------------------
		// 3. Grant creator caps to non-admins who are in the settings list.
		// ---------------------------------------------------------------
		$needs_creator_cap = false;
		foreach ( $caps as $cap ) {
			if ( in_array( $cap, self::CREATOR_CAPS, true ) ) {
				$needs_creator_cap = true;
				break;
			}
		}

		if ( $needs_creator_cap && Settings::user_can_create( $user_id ) ) {
			foreach ( $caps as $cap ) {
				if ( in_array( $cap, self::CREATOR_CAPS, true ) ) {
					$allcaps[ $cap ] = true;
				}
			}
		}

		// ---------------------------------------------------------------
		// 4. Always allow a non-admin to edit/delete their own READMEs,
		// regardless of whether they're still in the settings list.
		// Ownership is permanent — losing create access doesn't lock
		// someone out of posts they already wrote.
		// ---------------------------------------------------------------
		if ( $post_id > 0 ) {
			$post = get_post( $post_id );
			if (
				$post &&
				Post_Type::SLUG === $post->post_type &&
				Ownership::is_owner( $post_id, $user_id )
			) {
				// Grant any readmewp-related primitive cap (covers edit_readmewps,
				// edit_published_readmewps, delete_readmewps, delete_published_readmewps, etc.
				foreach ( $caps as $cap ) {
					if ( str_contains( $cap, 'readmewp' ) ) {
						$allcaps[ $cap ] = true;
					}
				}
			}
		}

		return $allcaps;
	}
}
